<?php

namespace Database\Seeders;

use App\Models\DocumentType;
use App\Models\Role;
use Illuminate\Database\Seeder;

class DocumentTypeSeeder extends Seeder
{
    public function run(): void
    {
        foreach ($this->documentTypes() as $type) {
            $roleNames = $type['roles'];
            unset($type['roles']);

            $documentType = DocumentType::updateOrCreate(
                ['code' => $type['code']],
                $type
            );

            $this->syncRoles($documentType, $roleNames);
        }
    }

    private function syncRoles(DocumentType $documentType, array $roleNames): void
    {
        $roleIds = Role::whereIn('name', $roleNames)->pluck('id')->all();

        $documentType->roles()->sync($roleIds);
    }

    private function documentTypes(): array
    {
        return [
            [
                'name' => 'Application',
                'code' => 'application',
                'category' => 'case_creation',
                'is_required' => true,
                'is_pleading' => true,
                'allows_multiple' => false,
                'sort_order' => 1,
                'is_active' => true,
                'roles' => ['alu_atty', 'alu_clerk', 'alu_paralegal', 'hu_clerk'],
            ],
            [
                'name' => 'Denial Letter',
                'code' => 'denial_letter',
                'category' => 'case_creation',
                'is_required' => false,
                'is_pleading' => false,
                'allows_multiple' => false,
                'sort_order' => 2,
                'is_active' => true,
                'roles' => ['alu_atty', 'alu_mgr', 'alu_paralegal'],
            ],
            [
                'name' => 'Letter Returning Application',
                'code' => 'letter_returning_application',
                'category' => 'case_creation',
                'is_required' => false,
                'is_pleading' => false,
                'allows_multiple' => false,
                'sort_order' => 3,
                'is_active' => true,
                'roles' => ['alu_atty', 'alu_clerk', 'alu_mgr'],
            ],
            [
                'name' => 'Letter Rejecting Application',
                'code' => 'letter_rejecting_application',
                'category' => 'case_creation',
                'is_required' => false,
                'is_pleading' => false,
                'allows_multiple' => false,
                'sort_order' => 4,
                'is_active' => true,
                'roles' => ['alu_atty', 'alu_clerk', 'alu_mgr', 'alu_paralegal'],
            ],
            [
                'name' => 'Letter(s) of Protest',
                'code' => 'protest_letter',
                'category' => 'case_creation',
                'is_required' => false,
                'is_pleading' => false,
                'allows_multiple' => true,
                'sort_order' => 5,
                'is_active' => true,
                'roles' => ['alu_atty', 'alu_clerk', 'alu_mgr', 'alu_paralegal'],
            ],
            [
                'name' => 'Notice(s) of Publication',
                'code' => 'notice_publication',
                'category' => 'case_creation',
                'is_required' => true,
                'is_pleading' => false,
                'allows_multiple' => true,
                'sort_order' => 6,
                'is_active' => true,
                'roles' => ['alu_atty', 'alu_clerk', 'alu_mgr', 'alu_paralegal'],
            ],
            [
                'name' => 'Affidavit(s) of Publication',
                'code' => 'affidavit_publication',
                'category' => 'case_creation',
                'is_required' => false,
                'is_pleading' => false,
                'allows_multiple' => true,
                'sort_order' => 7,
                'is_active' => true,
                'roles' => ['alu_atty', 'alu_clerk', 'alu_mgr', 'alu_paralegal'],
            ],
            [
                'name' => 'Web Posting of Notice of Publication',
                'code' => 'web_posting_notice',
                'category' => 'case_creation',
                'is_required' => false,
                'is_pleading' => false,
                'allows_multiple' => false,
                'sort_order' => 8,
                'is_active' => true,
                'roles' => ['alu_atty', 'alu_clerk', 'alu_mgr', 'alu_paralegal'],
            ],
            [
                'name' => 'Compliance Order',
                'code' => 'compliance_order',
                'category' => 'case_creation',
                'is_required' => false,
                'is_pleading' => false,
                'allows_multiple' => true,
                'sort_order' => 9,
                'is_active' => true,
                'roles' => ['alu_atty', 'alu_clerk', 'alu_mgr', 'alu_paralegal'],
            ],
            [
                'name' => 'Pre-Compliance Letter',
                'code' => 'pre_compliance_letter',
                'category' => 'case_creation',
                'is_required' => false,
                'is_pleading' => false,
                'allows_multiple' => true,
                'sort_order' => 10,
                'is_active' => true,
                'roles' => ['alu_atty', 'alu_clerk', 'alu_mgr', 'alu_paralegal'],
            ],
            [
                'name' => 'Compliance Letter',
                'code' => 'compliance_letter',
                'category' => 'case_creation',
                'is_required' => false,
                'is_pleading' => false,
                'allows_multiple' => true,
                'sort_order' => 11,
                'is_active' => true,
                'roles' => ['alu_atty', 'alu_clerk', 'alu_mgr', 'alu_paralegal'],
            ],
            [
                'name' => 'Notice of Violation',
                'code' => 'notice_of_violation',
                'category' => 'case_creation',
                'is_required' => false,
                'is_pleading' => false,
                'allows_multiple' => true,
                'sort_order' => 12,
                'is_active' => true,
                'roles' => ['alu_atty', 'alu_clerk', 'alu_mgr', 'alu_paralegal'],
            ],
            [
                'name' => 'Notice of Reprimand (Well Driller)',
                'code' => 'notice_of_reprimand',
                'category' => 'case_creation',
                'is_required' => false,
                'is_pleading' => false,
                'allows_multiple' => true,
                'sort_order' => 13,
                'is_active' => true,
                'roles' => ['alu_atty', 'alu_clerk', 'alu_mgr', 'alu_paralegal'],
            ],
            [
                'name' => 'Supporting documents',
                'code' => 'supporting',
                'category' => 'case_creation',
                'is_required' => false,
                'is_pleading' => false,
                'allows_multiple' => true,
                'sort_order' => 14,
                'is_active' => true,
                'roles' => ['alu_atty', 'alu_clerk', 'alu_mgr', 'alu_paralegal', 'external_attorney', 'party'],
            ],
            [
                'name' => 'Notice of Contemplated Action',
                'code' => 'notice_contemplated_action',
                'category' => 'case_creation',
                'is_required' => false,
                'is_pleading' => false,
                'allows_multiple' => false,
                'sort_order' => 15,
                'is_active' => true,
                'roles' => ['alu_atty', 'alu_clerk', 'alu_mgr', 'alu_paralegal'],
            ],
            [
                'name' => 'Cease and Desist Letter(s)',
                'code' => 'cease_desist_letter',
                'category' => 'case_creation',
                'is_required' => false,
                'is_pleading' => false,
                'allows_multiple' => true,
                'sort_order' => 16,
                'is_active' => true,
                'roles' => ['alu_atty', 'alu_clerk', 'alu_mgr', 'alu_paralegal'],
            ],
            [
                'name' => 'Others',
                'code' => 'other',
                'category' => 'case_creation',
                'is_required' => false,
                'is_pleading' => false,
                'allows_multiple' => true,
                'sort_order' => 17,
                'is_active' => true,
                'roles' => ['alu_atty', 'alu_clerk', 'alu_mgr', 'alu_paralegal', 'external_attorney', 'hu_admin', 'hu_clerk', 'party'],
            ],
            [
                'name' => 'Request for Pre-Hearing',
                'code' => 'request_pre_hearing',
                'category' => 'case_creation',
                'is_required' => false,
                'is_pleading' => true,
                'allows_multiple' => false,
                'sort_order' => 14,
                'is_active' => true,
                'roles' => ['alu_atty', 'alu_clerk', 'alu_mgr', 'alu_paralegal'],
            ],
            [
                'name' => 'Request to Docket',
                'code' => 'request_to_docket',
                'category' => 'case_creation',
                'is_required' => false,
                'is_pleading' => true,
                'allows_multiple' => false,
                'sort_order' => 18,
                'is_active' => true,
                'roles' => ['alu_atty', 'alu_clerk', 'alu_mgr', 'alu_paralegal'],
            ],
            [
                'name' => 'Motion',
                'code' => 'motion',
                'category' => 'party_upload',
                'is_required' => false,
                'is_pleading' => false,
                'allows_multiple' => false,
                'sort_order' => 1,
                'is_active' => true,
                'roles' => ['alu_clerk', 'alu_paralegal', 'external_attorney', 'party'],
            ],
            [
                'name' => 'Joint Motion',
                'code' => 'joint_motion',
                'category' => 'party_upload',
                'is_required' => false,
                'is_pleading' => false,
                'allows_multiple' => false,
                'sort_order' => 2,
                'is_active' => true,
                'roles' => [],
            ],
            [
                'name' => 'Stipulated Motion',
                'code' => 'stipulated_motion',
                'category' => 'party_upload',
                'is_required' => false,
                'is_pleading' => false,
                'allows_multiple' => false,
                'sort_order' => 3,
                'is_active' => true,
                'roles' => ['alu_atty', 'alu_clerk', 'alu_mgr', 'alu_paralegal', 'external_attorney', 'party'],
            ],
            [
                'name' => 'Unopposed Motion',
                'code' => 'unopposed_motion',
                'category' => 'party_upload',
                'is_required' => false,
                'is_pleading' => false,
                'allows_multiple' => false,
                'sort_order' => 4,
                'is_active' => true,
                'roles' => ['alu_atty', 'alu_clerk', 'alu_mgr', 'alu_paralegal', 'external_attorney', 'party'],
            ],
            [
                'name' => 'Motion for Status Conference',
                'code' => 'motion_status_conference',
                'category' => 'party_upload',
                'is_required' => false,
                'is_pleading' => false,
                'allows_multiple' => false,
                'sort_order' => 5,
                'is_active' => true,
                'roles' => ['alu_atty', 'alu_clerk', 'alu_mgr', 'alu_paralegal', 'external_attorney', 'party'],
            ],
            [
                'name' => 'Motion for Scheduling Conference',
                'code' => 'motion_scheduling_conference',
                'category' => 'party_upload',
                'is_required' => false,
                'is_pleading' => false,
                'allows_multiple' => false,
                'sort_order' => 6,
                'is_active' => true,
                'roles' => ['alu_atty', 'alu_clerk', 'alu_mgr', 'alu_paralegal', 'external_attorney', 'party'],
            ],
            [
                'name' => 'Motion to Dismiss',
                'code' => 'motion_to_dismiss',
                'category' => 'party_upload',
                'is_required' => false,
                'is_pleading' => false,
                'allows_multiple' => false,
                'sort_order' => 7,
                'is_active' => true,
                'roles' => ['alu_atty', 'alu_clerk', 'alu_mgr', 'alu_paralegal', 'external_attorney', 'party'],
            ],
            [
                'name' => 'Motion for Summary Judgment',
                'code' => 'motion_summary_judgment',
                'category' => 'party_upload',
                'is_required' => false,
                'is_pleading' => false,
                'allows_multiple' => false,
                'sort_order' => 8,
                'is_active' => true,
                'roles' => [],
            ],
            [
                'name' => 'Motion for Hearing',
                'code' => 'motion_for_hearing',
                'category' => 'party_upload',
                'is_required' => false,
                'is_pleading' => false,
                'allows_multiple' => false,
                'sort_order' => 9,
                'is_active' => true,
                'roles' => ['alu_atty', 'alu_clerk', 'alu_mgr', 'alu_paralegal', 'external_attorney', 'party'],
            ],
            [
                'name' => 'Notice of Pre-Hearing Scheduling Conference',
                'code' => 'notice_of_pre_hearing_scheduling_conference',
                'category' => 'system',
                'is_required' => false,
                'is_pleading' => false,
                'allows_multiple' => true,
                'sort_order' => 1,
                'is_active' => true,
                'roles' => ['hu_admin', 'hu_clerk'],
            ],
            [
                'name' => 'Docketing Order',
                'code' => 'docketing_order',
                'category' => 'system',
                'is_required' => false,
                'is_pleading' => false,
                'allows_multiple' => true,
                'sort_order' => 1,
                'is_active' => true,
                'roles' => ['hu_admin', 'hu_clerk'],
            ],
            [
                'name' => 'Scheduling Order',
                'code' => 'scheduling_order',
                'category' => 'system',
                'is_required' => false,
                'is_pleading' => false,
                'allows_multiple' => true,
                'sort_order' => 0,
                'is_active' => true,
                'roles' => ['hu_admin'],
            ],
            [
                'name' => 'Notice of Status Conference',
                'code' => 'notice_of_status_conference',
                'category' => 'system',
                'is_required' => false,
                'is_pleading' => false,
                'allows_multiple' => true,
                'sort_order' => 0,
                'is_active' => true,
                'roles' => ['hu_admin'],
            ],
            [
                'name' => 'Order Amending Scheduling Order',
                'code' => 'order_amending_scheduling_order',
                'category' => 'system',
                'is_required' => false,
                'is_pleading' => false,
                'allows_multiple' => true,
                'sort_order' => 0,
                'is_active' => true,
                'roles' => ['hu_admin'],
            ],
            [
                'name' => 'Order Dismissing Protestant(s)',
                'code' => 'order_dismissing_protest',
                'category' => 'system',
                'is_required' => false,
                'is_pleading' => false,
                'allows_multiple' => true,
                'sort_order' => 0,
                'is_active' => true,
                'roles' => ['hu_admin'],
            ],
            [
                'name' => 'Order Granting Extension of Time',
                'code' => 'order_granting_extension_of_time',
                'category' => 'case_creation',
                'is_required' => false,
                'is_pleading' => false,
                'allows_multiple' => true,
                'sort_order' => 0,
                'is_active' => true,
                'roles' => ['hu_admin'],
            ],
            [
                'name' => 'Order Dismissing Hearing',
                'code' => 'order_dismissing_hearing',
                'category' => 'system',
                'is_required' => false,
                'is_pleading' => false,
                'allows_multiple' => false,
                'sort_order' => 0,
                'is_active' => true,
                'roles' => ['hu_admin'],
            ],
            [
                'name' => 'Order Vacating and Rescheduling',
                'code' => 'order_vacating_and_rescheduling',
                'category' => 'system',
                'is_required' => false,
                'is_pleading' => false,
                'allows_multiple' => false,
                'sort_order' => 0,
                'is_active' => true,
                'roles' => ['hu_admin'],
            ],
            [
                'name' => 'Supporting documents to Application',
                'code' => 'supporting_documents_to_application',
                'category' => 'case_creation',
                'is_required' => false,
                'is_pleading' => false,
                'allows_multiple' => true,
                'sort_order' => 0,
                'is_active' => true,
                'roles' => ['alu_atty', 'alu_clerk', 'alu_paralegal'],
            ],
            [
                'name' => 'Motion for Summary Judgment',
                'code' => 'motion_for_summary_judgment',
                'category' => 'party_upload',
                'is_required' => false,
                'is_pleading' => false,
                'allows_multiple' => false,
                'sort_order' => 0,
                'is_active' => true,
                'roles' => ['alu_atty', 'alu_clerk', 'alu_mgr', 'alu_paralegal', 'external_attorney', 'party'],
            ],
            [
                'name' => 'Motion to Extend Deadlines',
                'code' => 'motion_to_extend_deadlines',
                'category' => 'case_creation',
                'is_required' => false,
                'is_pleading' => false,
                'allows_multiple' => false,
                'sort_order' => 0,
                'is_active' => true,
                'roles' => ['alu_atty', 'alu_clerk', 'alu_mgr', 'alu_paralegal', 'external_attorney', 'party'],
            ],
        ];
    }
}
